### ISSUE TITLE
Libreoffice Suite

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/pinbadge-icon-theme#4]
- [x] libreoffice
- [x] libreoffice-draw
- [x] libreoffice-math
- [x] libreoffice-writer
- [x] libreoffice-impress
- [x] libreoffice-base
- [x] libreoffice-calc

**Comment by loctauxphilippe** [comment]
you forgot calc :)

**Comment by crutchcorn** [comment]
I hate their naming scemes... I made base and then accidnetly overwrote it with calc -___-
