### ISSUE TITLE
SVGs tints messed up

### ISSUE THREAD

**Issue by saq1610** [crutchcorn/pinbadge-icon-theme#8]
Sorry for the bad quality. I hate windows.

![terminal_bug](https://cloud.githubusercontent.com/assets/10332349/10229956/94b2b9c6-682f-11e5-8ec9-dccaaff508dd.JPG)

**Comment by crutchcorn** [comment]
This is for the SVG correct?

**Comment by saq1610** [comment]
@crutchcorn Yes. but the attachment is a jpeg.

**Comment by crutchcorn** [comment]
THis is an export bug with AI.... I'll have to go back and manually fix all of the SVGs

**Comment by crutchcorn** [comment]
Okay, so I'm an idiot. Turns out all I needed to do was export the SVG using 3 decimal places rather than 1

**Comment by saq1610** [comment]
@crutchcorn How about using Inkscape?
