### ISSUE TITLE
Icon for nautilus

### ISSUE THREAD

**Issue by loctauxphilippe** [crutchcorn/pinbadge-icon-theme#9]
an icon for nautilus is missing
"nautilus.svg" for the name :)

**Comment by crutchcorn** [comment]
Nuh uh! You're missing! (no but seriously, I already knew about that. ;) )

**Comment by loctauxphilippe** [comment]
oh ok! no problem :)

**Comment by crutchcorn** [comment]
Finished the icon

**Comment by loctauxphilippe** [comment]
cool, works :)
